# -*- coding: utf-8 -*-
"""FMNSA_main_project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17AGDXp7_QrGc59Ljfl9IWwL0cWAOUs8H

# Finacial Market Newa - Sentiment Anlysis

#Import Library
"""

import pandas as pd
import numpy as np

"""# Objective

Sentiment analysis in financial markets aims to classify news and social media content as positive, negative, or neutral, providing valuable insights for traders. It involves assigning sentiment scores to assess emotional tone, real-time monitoring, and event detection. This analysis helps in risk management, trend identification, and automated trading strategies. Advanced NLP techniques and data sources are crucial for accurate sentiment assessment, aiding in informed decision-making in the dynamic world of finance.

#Import Dataset
"""

url = 'https://github.com/YBI-Foundation/Dataset/raw/main/Financial%20Market%20News.csv'
df = pd.read_csv(url, encoding='ISO-8859-1')

df.head()

df.describe()

df.info()

df.shape

df.columns

"""#Get Feature Selection"""

''.join(str(x) for x in df.iloc[1,2:27])

df.index

len(df.index)

news = []
for row in range (0,len(df.index)):
    news.append(''.join(str(x) for x in df.iloc[row, 2:27]))

type(news)

news[0]

x =news

type(x)

"""#Get Feature Text Conversion to Bag of Words"""

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(lowercase = True , ngram_range=(1,1))

x = cv.fit_transform(x)

x.shape

y = df['Label']

y.shape

"""#Get Train test Split"""

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 2529, train_size = 0.7)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=200)

rf.fit(x_train, y_train)

y_pred = rf.predict(x_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

accuracy_score(y_test, y_pred)

confusion_matrix(y_test, y_pred)

print(classification_report(y_test, y_pred))

"""# Explaination

1. **Sentiment Analysis Purpose**: Sentiment analysis in financial markets serves the purpose of determining the emotional tone or sentiment of financial news and social media content related to stocks, investments, and markets.

2. **Classification and Scoring**: It involves classifying this content as either positive (indicating optimism), negative (indicating pessimism), or neutral. Additionally, a sentiment score can be assigned to quantify the intensity of sentiment.

3. **Real-Time Insight**: This analysis provides real-time insights into how market participants perceive and react to financial news, helping traders and investors make informed decisions.

4. **Risk Management and Strategy**: It's a critical tool for risk management, allowing market participants to assess potential risks associated with sentiment shifts, and for developing automated trading strategies based on sentiment signals.

5. **Accuracy and Data Sources**: To ensure reliable results, sophisticated Natural Language Processing (NLP) techniques and diverse data sources, including news articles and social media platforms, are used for sentiment analysis in financial markets.
"""